name: Build/Test Cyclus

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.github/workflows/publish_latest.yml'
      - '.github/workflows/publish_release.yml'
      - '.github/workflows/changelog_test.yml'
      - '.github/workflows/code_coverage.yml'
      - 'doc/**'
      - 'CHANGELOG.rst'
  push:
    paths-ignore:
      - '.github/workflows/publish_latest.yml'
      - '.github/workflows/publish_release.yml'
      - '.github/workflows/changelog_test.yml'
      - '.github/workflows/code_coverage.yml'
      - 'doc/**'
      - 'CHANGELOG.rst'

jobs:
  build-test-cyclus:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        ubuntu_versions : [
          20.04,
          22.04,
        ]
        pkg_mgr : [
          apt,
          conda,
        ]

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout Cyclus
        uses: actions/checkout@v4

      - name: Build and Test Cyclus
        id: build-cyclus
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/cyclus_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cyclus:ci-layer-cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/cyclus_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cyclus:ci-layer-cache,mode=max
          tags: ghcr.io/${{ github.repository_owner }}/cyclus_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cyclus:ci-image-cache
          push: true
          build-args: |
            pkg_mgr=${{ matrix.pkg_mgr }}
            ubuntu_version=${{ matrix.ubuntu_versions }}

      - name: Checkout Cycamore
        if: ${{ github.event_name == 'pull_request' && steps.build-cyclus.outcome == 'success' }}
        uses: actions/checkout@v4
        with:
          repository: cyclus/cycamore
          path: ${{ github.workspace }}/cycamore

      - name: Build and Test Cycamore
        id: build-cycamore
        if: ${{ github.event_name == 'pull_request' && steps.build-cyclus.outcome == 'success' }}
        continue-on-error: true
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}/cycamore
          file: ${{ github.workspace }}/cycamore/docker/Dockerfile
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/cycamore_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cycamore:ci-layer-cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/cycamore_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cycamore:ci-layer-cache,mode=max
          tags: ghcr.io/${{ github.repository_owner }}/cycamore_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cycamore:ci-image-cache
          push: true
          build-args: |
            pkg_mgr=${{ matrix.pkg_mgr }}
            ubuntu_version=${{ matrix.ubuntu_versions }}
            cyclus_tag=ci-image-cache
          build-contexts: |
            ghcr.io/cyclus/cyclus_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cyclus:ci-image-cache=docker-image://ghcr.io/${{ github.repository_owner }}/cyclus_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cyclus:ci-image-cache@${{ steps.build-cyclus.outputs.digest }}

      - name: Checkout Cymetric
        if: ${{ github.event_name == 'pull_request' && steps.build-cycamore.outcome == 'success' }}
        uses: actions/checkout@v4
        with:
          repository: cyclus/cymetric
          path: ${{ github.workspace }}/cymetric

      - name: Build and Test Cymetric
        if: ${{ github.event_name == 'pull_request' && steps.build-cycamore.outcome == 'success' }}
        id: build-cymetric
        continue-on-error: true
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}/cymetric
          file: ${{ github.workspace }}/cymetric/docker/Dockerfile
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/cymetric_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cymetric:ci-layer-cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/cymetric_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cymetric:ci-layer-cache,mode=max
          build-args: |
            pkg_mgr=${{ matrix.pkg_mgr }}
            ubuntu_version=${{ matrix.ubuntu_versions }}
            cycamore_tag=ci-image-cache
          build-contexts: |
            ghcr.io/cyclus/cycamore_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cycamore:ci-image-cache=docker-image://ghcr.io/${{ github.repository_owner }}/cycamore_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cycamore:ci-image-cache@${{ steps.build-cycamore.outputs.digest }}

      - name: Export Environment Variables
        if: github.event_name == 'pull_request'
        run: |
          echo "CYCAMORE_BUILD_STATUS=${{steps.build-cycamore.outcome == 'success' && '**Success** :white_check_mark:' || 
          steps.build-cycamore.outcome == 'failure' && '**Failure** :x:' || 
          '**Skipped due to upstream failure** :warning:'}}" >> "$GITHUB_ENV"

          echo "CYMETRIC_BUILD_STATUS=${{steps.build-cymetric.outcome == 'success' && '**Success** :white_check_mark:' || 
          steps.build-cymetric.outcome == 'failure' && '**Failure** :x:' || 
          '**Skipped due to upstream failure** :warning:'}}" >> "$GITHUB_ENV"

          echo "ARTIFACT_NAME=${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}" >> "$GITHUB_ENV"

      - name: Construct Artifact
        if: github.event_name == 'pull_request'
        run: |
          echo "
          ##### Build \`FROM cyclus_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/cyclus\`
            - Cycamore: ${{ env.CYCAMORE_BUILD_STATUS }}
            - Cymetric: ${{ env.CYMETRIC_BUILD_STATUS }}" > ${{ env.ARTIFACT_NAME }}.txt
      
      - name: Upload Artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}.txt

  upload-pr-number:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Save PR number to file
        run: |
          echo "${{ github.event.number }}" > pr_number
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr_number