name: Build/Test for PR and collaborator push

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/build_test_publish.yml'
      - '.github/workflows/changelog_test.yml'
      - 'docker/**'
      - 'doc/**'
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/build_test_publish.yml'
      - '.github/workflows/changelog_test.yml'
      - 'docker/**'
      - 'doc/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ubuntu_versions : [
          22.04,
          ]
        pkg_mgr : [
            apt,
            conda
        ]

    container:
      image: ghcr.io/cyclus/cyclus_${{ matrix.ubuntu_versions }}_${{ matrix.pkg_mgr }}/${{ matrix.pkg_mgr }}-deps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Building Cyclus
        run: python install.py -j 2 --build-type=Release --core-version 999999.999999 

      - name: Cyclus Unit Tests
        run: /root/.local/bin/cyclus_unit_tests

      - name: Cyclus Python Tests
        run: pytest-3 tests