name: Standard Build and Test

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/docker_publish.yml'

  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/docker_publish.yml'


jobs:
  BuildTest:
    runs-on: ubuntu-latest 

    container:
      image: cyclus/cyclus-deps
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
         
      - name: Building DAGMC
        run: |
          cd $GITHUB_WORKSPACE
          python install.py -j 2 
                            --build-type=Release --core-version 999999.999999 \
                            -DBLAS_LIBRARIES="/opt/conda/lib/libblas.so" \
                            -DLAPACK_LIBRARIES="/opt/conda/lib/liblapack.so"

      - name: Unit Test
        run: |
          /root/.local/bin/cyclus_unit_tests; exit $?
      
      - name: Nosetest
        run: |
          nosetests -w ~/cyclus/tests; exit $?
